services:
  # web:
  #   build:
  #     context: ./frontend
  #   container_name: web
  #   networks:
  #     - app-network
  #   ports:
  #     - "${FRONTEND_PORT}:${FRONTEND_PORT}"
  #   env_file:
  #     - .env

  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - app-network
    env_file:
      - .env
    volumes:
      - ./server:/app
    depends_on:
      - db

  telegram_bot:
    build:
      context: ./telegram
    container_name: telegram_bot
    networks:
      - app-network
    env_file:
      - .env
    volumes:
      - ./telegram:/app

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./scripts/nginx.conf.prod:/etc/nginx/nginx.conf.prod
      - ./scripts/nginx.conf.dev:/etc/nginx/nginx.conf.dev
      - ./scripts/ssl:/etc/nginx/ssl
      - ./scripts/nginx_setup.sh:/nginx_setup.sh
    entrypoint: ["/nginx_setup.sh"]
    depends_on:
      - server
    networks:
      - app-network
    environment:
      - DOMAIN=${DOMAIN}
      - ENVIRONMENT=${ENVIRONMENT}
      - SERVER_PORT=${SERVER_PORT}
    env_file:
      - .env

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - app-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app-network:
    driver: bridge
    # driver_opts:
    #   com.docker.network.driver.mtu: 1450

  